### ISSUE TITLE
Add dynamic info

### ISSUE THREAD

**Issue by potomak** [tareq1988/woocommerce-conversion-tracking#1]
It should be possible to add dynamic segments to the code added.

Example:

```html
<script>
_tracking.push({price: [product-price], name: [product-name]});
</script>

**Comment by tareq1988** [comment]
Thats a good feature request :)

**Comment by paxmanchris** [comment]
I started to write my own code to do conversion tracking, then I found this.  
I agree with @potomak :+1: 

I will be forking this project and taking a stab at implementing this feature.

I would add bracket tags like this:
```
var google_conversion_value = {order_subtotal};
var google_conversion_currency = {currency};
```
There could be other options like, `{order_total}` or `{order_total_before_shipping}`. Then I would just do a str_replace for the real values.

**Comment by tareq1988** [comment]
Please submit a pull request when you are done :)

**Comment by paxmanchris** [comment]
I submitted a pull request https://github.com/tareq1988/woocommerce-conversion-tracking/pull/3. Did you have a chance to look at it.

**Comment by tareq1988** [comment]
Featured added on `v1.1`
