### ISSUE TITLE
Namespaced classes

### ISSUE THREAD

**Issue by gp0** [tareq1988/woocommerce-conversion-tracking#30]
Hey,
it would be great if the classes would be Namespaced, otherwise your plugin collides with other plugins ("PHP Fatal error:  Cannot redeclare class WCCT_Admin"). If namespaces aren't an option please consider a prefix to make the class names more unique.

**Comment by tareq1988** [comment]
**W**oo**C**ommerce**C**onversion**T**racking is already prefixed. Which other plugin is conflicting with such class name? That would be a real coincidence.

**Comment by gp0** [comment]
It's [this one](https://wordpress.org/plugins/finale-woocommerce-sales-countdown-timer-discount/). I'm not the author, just ran into it randomly, because a client of mine wanted to try it out, and i figured i'd just let you know.

Probably niche-ish use case, but in my opinion, using the PHP namespaces would still be a good idea, depends on how much backwards compatability you want to maintain, afaik Woocommerce recommends PHP7, so one could argue that using PHP namespaces would be okay.

**Comment by tareq1988** [comment]
I'm all in for using namespace and other PHP > 5.4 functionalities, but backwards compatibility is the main killer for plugin developers.

**Comment by gp0** [comment]
For now, i've patched in a prefix in the other plugin and can live with that workaround.
