### ISSUE TITLE
Product Catalog Issue in paid version 

### ISSUE THREAD

**Issue by shabnam611** [tareq1988/woocommerce-conversion-tracking#38]
Description: "File format is not supported" when catalog feed is uploaded 

How to Reproduce the Issue: 

Please navigate through inside the FaceBook catalog manager > create catalog > configure the settings according to the setup instructions of WooCommerce Conversion Tracking plugin. 

When product data feed is copied by the user and added in the setup feed, the system throws the error.

Expected behavior: The product data feed should be accepted by facebook catalog manager correctly

**Comment by tareq1988** [comment]
@hasinur1997 can you check this issue?

**Comment by hasinur1997** [comment]
I have checked the issue and have to change the process of our plugin. I will update the process as soon as possible.
