### ISSUE TITLE
Warning message on PHP5.6

### ISSUE THREAD

**Issue by mayukojpn** [tareq1988/woocommerce-conversion-tracking#7]
Hi! Thank you for great plugin.
I'll report warning message I found when I activate plugin.

I used WordPress `PHP5.6` `WordPress 4.7.2` with `define( 'WP_DEBUG', true );`
> Strict Standards: Declaration of WeDevs_WC_Tracking_Integration::validate_textarea_field() should be compatible with WC_Settings_API::validate_textarea_field($key, $value) in /var/www/wordpress/wp-content/plugins/woocommerce-conversion-tracking/includes/integration.php on line 0

**Comment by tareq1988** [comment]
Fixed in #6
